%
O00001 (INFO)
(ZAGOTOVKA VERTIKALNO) 
(POD 90 GRAD K TISKAM) 
(X0 Y0 CENTR) 
(Z0 NIZ TISOV +PODKLADKA+DETAL) 
(V PROGRAME TOREC - SNACHALA ODNU STORONU) 
(PREDVARITELNO) 
(POTOM 2 OKONCHATELNO V RAZMER POSLE RAZVOROTA) 






%