%
O00001 (INFO 1 USTANOV) 

(DETAL ZAGATA ZA TRUBU V TISA) 
(MOLOT  SLEVO) 
(VIKATAT INDIKATOROM PLOSKOST MOLOTA  PO  Z ) 
(MEGDU TISAMI I MOLOTOM 35+-1.  [PODKLADKA]) 
() 



(X0 SPRAVO) 
(Y0 CENTR DETALI) 
(Z0 VERH MOLOTA  NA TORCE V ZAGOTOVKE  PRIPUSK +1 MM[ SLEVO ] ) 





%