%
O00038 (INFO 2 USTANOV) 

(DETAL VERTIKALNO NA STOLE MOLOTOM VERH.. TRUBA DAL) 
(ZAGATO ZA NIZ I VISOKIM PRIGIMOM I 2 DETAL VERH) 


(X0 CENTR) 
(Y0 BLIZ PLOSKOST) 
(Z0 PLOSKOST OTV) 



%